eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8092


spring:
  application:
    name: clients

  data:
    mongodb:
      host: localhost
      port: 27017
      database: clients
management:
  tracing:
    sampling:
      probability: 1.0