
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8777


spring:
  application:
    name: formulaire

  data:
    mongodb:
      host: localhost
      port: 27017
      database: solarchain

management:
  tracing:
    sampling:
      probability: 1.0